#!/bin/sh

INPUT=$1
ALBUM=${2:-Album}

[ -z "$INPUT" ] && echo "Please provide an input file" && exit

if [ -e ./ProcList.csv ]
then
	[ ! -d ./Tracks ] && mkdir ./Tracks 
	TOTALTRACKS=$(wc -l ./ProcList.csv | awk '{print $1}')
	for TRACK in $(seq 1 $TOTALTRACKS)
	do
		TRACKSTART=$(awk -F, '$1 == '$TRACK' {print $2}' ./ProcList.csv)
		TRACKEND=$(awk -F, '$1 == '$TRACK' {print $3}' ./ProcList.csv)

		TRACKNUMBER=$(awk -F, '$1 == '$TRACK' {print $1}' ./ProcList.csv)
		TRACKNAME=$(awk -F, '$1 == '$TRACK' {print $4}' ./ProcList.csv)
		TRACKARTIST=$(awk -F, '$1 == '$TRACK' {print $5}' ./ProcList.csv)

		ffmpeg -i "$INPUT" -ss $TRACKSTART -to $TRACKEND -c copy ./Tracks/output.mp3

		taffy --track "$TRACKNUMBER" --album "$ALBUM" --artist "$TRACKARTIST" --title "$TRACKNAME" --rename-fs "%n - %R - %T" ./Tracks/output.mp3

	done
else
	echo There\'s no \'ProcList\' file. Please create one.
fi
